name: Unit Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Modern:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [macos-latest] # ubuntu-latest, debian-latest, windows-latest
    env:
      CHANGED_SINCE: true # only run test on previously commit files
      MAIN_BRANCH: origin/main  # specify which branch to diff when running tests
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out
        uses: actions/checkout@v2
        run: |
          git fetch --no-tags --depth=1 origin main
          git checkout -b main
          git checkout ${{ github.event.pull_request.head.sha }}

      - name: Init
        run: npm install -g pnpm rimraf && pnpm run setup

      - name: Prepare
        run: pnpm run prepare --filter ./packages

      - name: Test
        run: cd packages/generator/generator-cases && pnpm run test
